name: value
description: A simple take on DDD ValueObjects
version: 0.0.1
homepage: https://book.kalbarczyk.co

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  freezed_annotation: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  freezed: ^2.0.3+1
  build_runner:
  json_serializable:
