name: value
description: A simple take on DDD ValueObjects
version: 0.0.14
homepage: https://github.com/adriank/value

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  validators: ^3.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.3
