name: value
description: A simple take on DDD ValueObjects
version: 0.0.9
homepage: https://book.kalbarczyk.co

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  validators: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  freezed: ^2.2.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.4
